server:
  port: 32618


spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: CryptGuardUseTest
          uri: lb://CryptGuardUseTest
          predicates:
            - Path=/api/crypt/**
          filters:
            - StripPrefix=2

    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: dev

custom:
  crypt:
    enable: true
    privateKey: "fang"
    deCryptUrls:
      - /api/crypt/decrypt/*
    enCryptUrls:
      - /api/*
